export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_COCKTAILS = 'FETCH_COCKTAILS';
export const FETCH_SINGLE_COCKTAIL = 'FETCH_SINGLE_COCKTAIL';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';